import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ChevronLeft, ChevronRight, Layers3, Menu, Microscope, Moon, MoveUpRight, ScanLine, Sun, X } from 'lucide-react';
import './styles.css';
import './blend.css';

const products = [
  { n:'01', icon: Layers3, name:'ZE/PATCH M1', type:'Microneedle platform', text:'A skin-friendly microneedle array designed to explore less invasive sensing and delivery for diabetes care.', stat:'μm-scale', label:'needle architecture' },
  { n:'02', icon: ScanLine, name:'ZE/SENSE G1', type:'Glucose sensing research', text:'A compact research platform investigating interstitial-fluid signals for simpler glucose monitoring.', stat:'Continuous', label:'signal exploration' },
  { n:'03', icon: Microscope, name:'ZE/DELIVER D1', type:'Therapeutic delivery research', text:'Controlled microneedle delivery concepts developed around comfort, consistency, and everyday use.', stat:'Low-profile', label:'wearable format' }
];
const heroSlides=[
  {image:'/assets/hero-microneedle-diabetes.png',kicker:'Microneedle research · thoughtfully engineered',lead:'A gentler path to',emphasis:'diabetes care.',copy:'Zearup is exploring microneedle technologies that could make glucose sensing and therapeutic delivery simpler, more comfortable, and easier to live with.',note:'Small-scale engineering for everyday care.'},
  {image:'/assets/hero-glucose-sensing.png',kicker:'Glucose sensing · research in progress',lead:'Listen closer to',emphasis:'glucose signals.',copy:'Our sensing research pairs a fine microneedle interface with compact electronics to study interstitial-fluid glucose signals.',note:'A wearable concept designed around quieter monitoring.'},
  {image:'/assets/hero-microneedle-delivery.png',kicker:'Microneedle delivery · early research',lead:'Delivery designed',emphasis:'around daily life.',copy:'We are investigating low-profile microneedle delivery concepts that prioritize comfort, control, and ease of use.',note:'A research platform—not yet a commercial medical device.'},
  {image:'/assets/microneedle-lab-research.png',kicker:'Prototype validation · inside the lab',lead:'Built through',emphasis:'careful testing.',copy:'Every array begins at the bench, where geometry, materials, sensing performance, and repeatability are evaluated together.',note:'Evidence first, from material to prototype.'}
];

function Logo(){ return <a className="logo" href="#/" aria-label="Zearup Biomed home"><svg className="logo-mark" viewBox="0 0 58 46" role="img" aria-label="Zearup symbol"><defs><linearGradient id="zg" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#50A7EF"/><stop offset="1" stopColor="#003468"/></linearGradient></defs><path fill="url(#zg)" d="M12 4 50 11c4 .8 5.2 6 2 8.5L35.7 32 49 35l-4 9-36-8c-4.5-1-5.5-6.8-1.8-9.4L24 15.5 9.2 13z"/><path fill="#50A7EF" opacity=".72" d="M24 15.5 42 19 29 29 7.2 26.6z"/></svg><span className="wordmark"><b>zearup</b><small>biomed</small></span></a> }
function Button({children,light=false,href='#/contact'}){ return <a className={`button ${light?'light':''}`} href={href}>{children}<ArrowRight size={16}/></a> }
function Header({theme,setTheme,home}){
  const [open,setOpen]=useState(false);
  const [navState,setNavState]=useState('nav-top');const lastY=useRef(0);
  useEffect(()=>{if(!home){setNavState('nav-static');return}lastY.current=scrollY;const onScroll=()=>{const y=scrollY;if(y<40)setNavState('nav-top');else if(y>lastY.current+5)setNavState('nav-hidden');else if(y<lastY.current-5)setNavState('nav-floating');lastY.current=y};addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[home]);
  return <header className={`site-header ${home?'home-nav':''} ${navState}`}><Logo/><nav className={open?'open':''}>{[['Products','#/products'],['About us','#/about'],['Contact','#/contact']].map(x=><a key={x[0]} href={x[1]} onClick={()=>setOpen(false)}>{x[0]}</a>)}<button className="theme-mobile" onClick={()=>setTheme(theme==='verdant'?'mineral':'verdant')}>Switch theme</button></nav><div className="header-actions"><button className="theme" aria-label="Change color theme" onClick={()=>setTheme(theme==='verdant'?'mineral':'verdant')}>{theme==='verdant'?<Moon size={16}/>:<Sun size={16}/>}</button><Button>Start a conversation</Button><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></header>
}
function Footer(){return <footer><div className="footer-lead"><p>Building better interfaces for diabetes care.</p><h2>Let’s make small technology<br/>matter every day.</h2><Button light>Talk to our team</Button></div><div className="footer-bottom"><div><Logo/><p>Microneedle research for diabetes care.</p></div><div className="footer-links"><div><b>Explore</b><a href="#/products">Research platform</a><a href="#/about">About us</a></div><div><b>Connect</b><a href="mailto:hello@zearup.com">hello@zearup.com</a><a href="#/contact">Contact</a></div></div></div><div className="legal"><span>© 2026 Zearup Biotechnology</span><span>Toronto · Canada</span></div></footer>}
function ProductCard({p}){const Icon=p.icon;return <article className="product-card"><div className="product-top"><span>{p.n}</span><Icon size={30}/></div><div><small>{p.type}</small><h3>{p.name}</h3><p>{p.text}</p></div><div className="product-stat"><strong>{p.stat}</strong><span>{p.label}</span></div><a href="#/contact">Explore system <ArrowRight size={15}/></a></article>}
function HeroCarousel(){const [active,setActive]=useState(0);const [paused,setPaused]=useState(false);useEffect(()=>{if(paused)return;const id=setInterval(()=>setActive(x=>(x+1)%heroSlides.length),6000);return()=>clearInterval(id)},[paused]);const slide=heroSlides[active];return <section className="hero" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}>{heroSlides.map((item,i)=><div className={`hero-bg hero-slide ${i===active?'active':''}`} style={{backgroundImage:`linear-gradient(90deg,rgba(0,52,104,.94) 0%,rgba(0,52,104,.62) 46%,rgba(80,167,239,.08)),url('${item.image}')`}} key={item.image}/>)}<div className="hero-content hero-copy-swap" key={active}><p className="eyebrow light-text">{slide.kicker}</p><h1>{slide.lead}<br/><em>{slide.emphasis}</em></h1><p className="hero-copy">{slide.copy}</p><Button light href="#/products">Explore our research</Button></div><div className="hero-note"><span>{String(active+1).padStart(2,'0')}</span><p>{slide.note}</p></div><div className="hero-dots" role="tablist" aria-label="Hero slides">{heroSlides.map((_,i)=><button className={i===active?'active':''} onClick={()=>setActive(i)} aria-label={`Show slide ${i+1}`} aria-selected={i===active} role="tab" key={i}><i/></button>)}</div></section>}
function ResearchCarousel(){const [active,setActive]=useState(0);const [paused,setPaused]=useState(false);const stories=[{image:'/assets/hero-microneedle-diabetes.png',tag:'Microneedle architecture',title:'Engineering at the scale of comfort',copy:'Studying array geometry and materials that can create a reliable interface with minimal disruption to daily life.'},{image:'/assets/hero-glucose-sensing.png',tag:'Glucose sensing',title:'Exploring signals beneath the surface',copy:'Evaluating how a wearable microneedle interface could support consistent interstitial-fluid glucose measurements.'},{image:'/assets/hero-microneedle-delivery.png',tag:'Delivery concepts',title:'Designed for controlled delivery',copy:'Prototyping low-profile patch and applicator formats for future diabetes therapy research.'},{image:'/assets/microneedle-lab-research.png',tag:'Prototype validation',title:'Testing every layer of the platform',copy:'Characterizing materials, mechanics, sensing response, and repeatability before concepts move forward.'}];useEffect(()=>{if(paused)return;const id=setInterval(()=>setActive(x=>(x+1)%stories.length),5000);return()=>clearInterval(id)},[paused]);const move=d=>setActive(x=>(x+d+stories.length)%stories.length);return <section className="research-carousel" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}><div className="research-heading"><div><p className="eyebrow">Inside the lab</p><h2>Microneedle research in <em>progress.</em></h2></div><div className="research-controls"><button onClick={()=>move(-1)} aria-label="Previous research story"><ChevronLeft/></button><span>{String(active+1).padStart(2,'0')} / {String(stories.length).padStart(2,'0')}</span><button onClick={()=>move(1)} aria-label="Next research story"><ChevronRight/></button></div></div><div className="research-track">{stories.map((s,i)=><button className={`research-card ${i===active?'active':''}`} onClick={()=>setActive(i)} key={s.title}><img src={s.image} alt={s.title}/><span className="research-shade"/><span className="research-card-copy"><small>{s.tag}</small><strong>{s.title}</strong><p>{s.copy}</p></span></button>)}</div></section>}
function WorkflowShowcase(){const [active,setActive]=useState('');const asset='/assets/microneedle-system-showcase.png';return <section className={`workflow-showcase ${active?`${active}-active`:''}`}><a className="showcase-cta left" href="#/contact" onMouseEnter={()=>setActive('left')} onMouseLeave={()=>setActive('')}><span>+</span><strong>Talk to the team</strong><small>Discuss a research collaboration</small></a><div className="showcase-media"><img className="showcase-base" src={asset} alt="Microneedle patch, applicator, sensing reader, and research cartridges"/><span className="lift-object lift-left"><i/></span><span className="lift-object lift-right"><i/></span><p>{active==='left'?'Collaboration starts here':active==='right'?'Explore the platform':'Hover either side to explore'}</p></div><a className="showcase-cta right" href="#/products" onMouseEnter={()=>setActive('right')} onMouseLeave={()=>setActive('')}><span>+</span><strong>Explore the platform</strong><small>See sensing and delivery concepts</small></a></section>}
function PrinciplesSection(){const items=[['01','Repeatable by design','Consistent results across operators and changing research demands.'],['02','Built around the bench','Clear controls shaped around the routines laboratory teams already know.'],['03','Open as you grow','Flexible protocols that evolve with new samples, methods, and discoveries.']];return <section className="principles"><div className="principles-intro"><p className="eyebrow">Why Zearup</p><h2>Research tools should make precision feel simple.</h2><Button href="#/about">How we work</Button></div><div className="principles-grid">{items.map(item=><article key={item[0]}><span>{item[0]}</span><div><h3>{item[1]}</h3><p>{item[2]}</p></div><MoveUpRight size={18}/></article>)}</div></section>}
function Home(){return <><HeroCarousel/><section className="intro"><p className="eyebrow">Built for everyday diabetes research</p><h2>Small interfaces can change the care experience.</h2><div className="intro-visual"><img src="/assets/microneedle-lab-research.png" alt="Researcher inspecting a translucent microneedle patch prototype"/><span><b>From material to prototype</b><small>Microneedle validation · Zearup Biomed</small></span></div><div className="intro-meta"><p>Microneedles create a new interface with the body. Zearup is studying how that interface could support gentler glucose sensing and more considered therapeutic delivery.</p><a href="#/about">Discover our approach <MoveUpRight size={18}/></a></div></section><section className="products-section"><div className="section-heading"><div><p className="eyebrow">Our research platform</p><h2>One microneedle platform.<br/><em>Two paths forward.</em></h2></div><p>We bring patch design, glucose-sensing research, and controlled-delivery concepts into one modular development platform.</p></div><div className="product-grid">{products.map(p=><ProductCard p={p} key={p.name}/>)}</div></section><ResearchCarousel/><PrinciplesSection/><WorkflowShowcase/></>}
function PageHero({kicker,title,copy}){return <section className="page-hero"><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{copy}</p></section>}
function Products(){return <><PageHero kicker="The Zearup research platform" title={<>One interface.<br/><em>Multiple possibilities.</em></>} copy="A modular microneedle platform for studying glucose sensing and controlled delivery in future diabetes-care applications."/><section className="product-list">{products.map((p,i)=>{const Icon=p.icon;return <article key={p.name}><div className="list-number">{p.n}</div><div className="device-art"><Icon size={74}/><span/></div><div className="list-copy"><small>{p.type}</small><h2>{p.name}</h2><p>{p.text}</p><div className="feature-chips"><span>Research-stage</span><span>Modular</span><span>Human-centered</span></div><Button>Request details</Button></div></article>})}</section></>}
function About(){return <><PageHero kicker="About Zearup" title={<>We are making microneedles<br/>feel more <em>human.</em></>} copy="Zearup is an early-stage biotechnology company researching microneedle interfaces for future diabetes sensing and delivery applications."/><section className="about-image"><div/><p>“The smallest interface can make a meaningful difference in everyday care.”</p></section><section className="story"><div><p className="eyebrow">Our point of view</p><h2>Designed around life with diabetes.</h2></div><div><p>Diabetes care asks people to make repeated decisions every day. We believe the technologies supporting those decisions should be less intrusive, easier to understand, and designed with daily routines in mind.</p><p>Our team brings together microneedle engineering, materials research, biosensing, and product design to investigate new ways of sensing glucose and delivering therapeutics. Our concepts remain research-stage and are not approved medical devices.</p></div></section><section className="values"><p className="eyebrow">What guides us</p><div>{[['01','Evidence','Let careful research lead every decision.'],['02','Comfort','Design around the person, not only the technology.'],['03','Possibility','Explore new interfaces for diabetes care.']].map(v=><article key={v[0]}><span>{v[0]}</span><h3>{v[1]}</h3><p>{v[2]}</p></article>)}</div></section></>}
function Contact(){return <section className="contact-page"><div className="contact-copy"><p className="eyebrow">Contact us</p><h1>Let’s move microneedle<br/>research <em>forward.</em></h1><p>Tell us about your diabetes research, sensing work, delivery program, or potential collaboration. Our team will be in touch shortly.</p><div className="contact-details"><span>Email</span><a href="mailto:hello@zearup.com">hello@zearup.com</a><span>Location</span><p>Toronto, Canada</p></div></div><form onSubmit={e=>{e.preventDefault();e.currentTarget.classList.add('sent')}}><label>Name<input required placeholder="Your name"/></label><label>Work email<input required type="email" placeholder="you@company.com"/></label><label>Company<input placeholder="Company or institution"/></label><label>How can we help?<textarea required placeholder="Tell us about your research or collaboration idea" rows="5"/></label><button className="button" type="submit">Send inquiry <ArrowRight size={16}/></button><p className="success">Thanks — your message is ready for our team.</p></form></section>}
function ScrollIndicator(){const [thumb,setThumb]=useState({top:0,height:0,visible:false});useEffect(()=>{let timer;const update=()=>{const root=document.documentElement;const max=root.scrollHeight-innerHeight;const height=Math.max(44,innerHeight*(innerHeight/root.scrollHeight));const top=max>0?(scrollY/max)*(innerHeight-height):0;setThumb({top,height,visible:max>0});document.body.classList.add('is-scrolling');clearTimeout(timer);timer=setTimeout(()=>document.body.classList.remove('is-scrolling'),650)};const resize=()=>{update();document.body.classList.remove('is-scrolling')};addEventListener('scroll',update,{passive:true});addEventListener('resize',resize);resize();return()=>{removeEventListener('scroll',update);removeEventListener('resize',resize);clearTimeout(timer)}},[]);return <div className={`scroll-indicator ${thumb.visible?'available':''}`} aria-hidden="true"><i style={{height:thumb.height,transform:`translateY(${thumb.top}px)`}}/></div>}
function MotionEffects({path}){useEffect(()=>{const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)return;const nodes=[...document.querySelectorAll('.intro,.section-heading,.product-card,.principles>*,.workflow-showcase,.page-hero>*,.product-list article,.about-image,.story>*,.values article,.contact-page>*,.footer-lead,.footer-bottom')];nodes.forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--delay',`${Math.min(i%3,2)*90}ms`)});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -7%'});nodes.forEach(el=>observer.observe(el));const hero=document.querySelector('.hero');const move=e=>{if(!hero)return;hero.style.setProperty('--mx',`${(e.clientX/innerWidth-.5)*12}px`);hero.style.setProperty('--my',`${(e.clientY/innerHeight-.5)*8}px`)};const scrollMotion=()=>hero?.style.setProperty('--hero-y',`${Math.min(scrollY*.12,70)}px`);addEventListener('pointermove',move,{passive:true});addEventListener('scroll',scrollMotion,{passive:true});return()=>{observer.disconnect();removeEventListener('pointermove',move);removeEventListener('scroll',scrollMotion)}},[path]);return null}
function App(){const [theme,setTheme]=useState(localStorage.getItem('zearup-theme')||'verdant');const [path,setPath]=useState(location.hash.slice(1)||'/');useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('zearup-theme',theme)},[theme]);useEffect(()=>{const f=()=>{setPath(location.hash.slice(1)||'/');scrollTo(0,0)};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const Page=path.startsWith('/products')?Products:path.startsWith('/about')?About:path.startsWith('/contact')?Contact:Home;const home=path==='/';return <><Header theme={theme} setTheme={setTheme} home={home}/><main><Page/></main><Footer/><ScrollIndicator/><MotionEffects path={path}/></>}

createRoot(document.getElementById('root')).render(<App/>);
